.github/workflows/release.yml, package.json
- check input properly to prevent adding pre-release tag always
- push commit changes so that version bumps are committed
=> chore: fix gh action step by pushing commit and checking prerelease input

src/cli/organizationsCLIController.ts, src/cli/projectsCLIController.ts, src/extension.ts, src/utils/loadRepoConfig.ts
Currently when we call StateManager.clearState in the refresh code usages command, it wipes out the repo config which breaks the alias matching. this way we'll reload the config before using it if it's not currently in state
=> Add wrapper to get repo config

media/vscode.css, package.json, src/cli/baseCLIController.ts, src/components/StartupViewProvider.ts, src/extension.ts, src/scripts/startup.ts, src/utils/setUpViews.ts
- add startup views
- install cli view with code snippet and installed button(added this button to get the next view)
- open workspace view
- add error message popup
- removed open workspace error message popup
=> feat: add sidebar views for install cli and open folder

package.json, src/components/SidebarProvider.ts, src/components/UsagesTree/FolderNode.ts, src/components/UsagesTree/UsagesTreeProvider.ts, src/extension.ts
If the current workspace contains multiple folders, split the code usages sidebar by folder. If only one folder exists, do not show a dropdown. Previously only the first folder would be displayed
=> feat: Split code usages by folder if multiple are open

src/scripts/startup.ts, src/views/startup/StartupViewProvider.ts
- update workspace button to show cli start up view after clicking it
- update installed cli button to refresh usages after clicking it
- remove `webviewView.webview.html = this._getHtmlForWebview(webviewView.webview, STARTUP_VIEWS.WORKSPACE)` on cli installed button clicked as we change the view order of "open workspace" and "install cli"
=> chore: udpate cli installed and workspace button logic

src/cli/OrganizationsCLIController.ts, src/cli/ProjectsCLIController.ts
Include folder name when prompting for an org or project to give the user context
=> fix: Add folder name to org/project prompt

src/extension.ts
When the folders in a workspace are changed, login to any new folders and then refresh code usages
=> fix: Refresh code usages when workspace folders change

package.json, src/cli/AuthCLIController.ts, src/cli/ProjectsCLIController.ts, src/extension.ts
Remove `loggedIn` and `repoConfigured` setContext commands:
`loggedIn` - set in multiple places but not used
`repoConfigured` - not relevant to enabling code usages, and not necessary to enable repo init (should be scoped by folder to actually work as intended)
=> chore: Remove unused commands

.gitignore, package.json, src/cli/AuthCLIController.ts, src/cli/BaseCLIController.test.ts, src/cli/BaseCLIController.ts, src/cli/utils/execShell.ts, src/cli/utils/index.ts, src/cli/utils/loadCli.ts, src/constants.ts, src/extension.ts, src/utils/index.ts, src/utils/showDebugOutput.ts, src/views/startup/StartupViewProvider.ts, src/views/startup/registerStartupViewProvider.ts, src/views/startup/utils/setUpViews.ts, yarn.lock
Download DVC CLI from github release when the extension is activated (if it doesn't already exist)
- Read tarball artifact as a stream and write to file
- Extract file into extension root
- Remove view that prompts user to install CLI
=> feat: Download cli on extension install

package.json, src/cli/VariablesCLIController.ts, src/commands/index.ts, src/commands/sortUsages/constants.ts, src/commands/sortUsages/executeSortUsagesCommand.ts, src/commands/sortUsages/index.ts, src/commands/sortUsages/registerSortUsagesCommand.ts, src/extension.ts, src/views/usages/UsagesTree/CodeUsageNode.ts, src/views/usages/UsagesTree/UsagesTreeProvider.ts
- Add sort button to the sidebar view title bar
- That button has a dropdown containing a submenu with the three different sorting criteria 
- Add the createdAt and updatedAt fields as children in the usages tree so that they can be used for sorting (and also be visible to the user)
EDIT: 
- will now sort descending if you sort by the same criteria twice in a row
- 
TODO still:
- Add some tests (will probably need to refactor the sorting login out into a utility function because Instantiating the UsagesTreeProvider class in a test is gonna be a whole separate can of worms)
=> add option to sort usages by key, created date, and updated date

src/cli/utils/loadCli.ts
If the installed cli version does not match the version pinned in the release, consider the cli not installed and load the pinned version
=> fix: Update installed cli version if it  does not match pinned version

src/cli/VariablesCLIController.test.ts, src/cli/VariablesCLIController.ts, src/views/usages/UsagesTree/CodeUsageNode.ts, src/views/usages/UsagesTree/UsagesTreeProvider.ts
Only show code usages in the variables list (not all variables from the API)
Note: the getAllVariables call still only returns the first 100 variables, so many variables will be incorrectly flagged as not in devcycle — this will be fixed in a follow up PR
=> feat: Only show code usages in variables list

src/cli/VariablesCLIController.test.ts, src/cli/VariablesCLIController.ts, src/constants.ts
Use CLI pagination params to fetch 1000 variables rather than default 100
Depends on CLI release of https://github.com/DevCycleHQ/cli/pull/264
=> fix: Use per-page param to fetch 1000 variables

.devcycle/config.yml, src/constants.ts, src/extension.ts, src/utils/credentials.ts
If the extension loads with an expired access token, the CLI will exchange the refresh token for a new access token. Currently multiple `dvc status` requests are sent simultaneously, which results in all but the first failing (because the refresh token is invalidated after it's used once).
- Load initial repo configs synchronously to allow the token to be refreshed if necessary
- Add repo config
- Bump CLI version
=> fix: Prevent multiple CLI requests when initializing extension

src/StateManager.ts
- clearState will no longer delete the project_id and organization from workspace folders
- Update clearFolderState to mirror that behaviour
=> fix project id getting cleared when it shouldnt be

package.json
- the settings(gear) icon was showing everywhere in vscode, fixed by putting it on the home view
=> fix: settings button shows only on home view

package.json, src/StateManager.ts, src/cli/UsagesCLIController.test.ts, src/cli/UsagesCLIController.ts, src/components/hoverCard.ts, src/extension.ts, src/views/usages/UsagesTree/UsagesTreeProvider.ts
- Add a setting (defaulting to true) to refresh code usages after a file is changed. Now when a user adds a variable usage the hover card will appear after saving
- Update codes usage keys in StateManager to be an object rather than an array so that it's a constant lookup
- Display the hover card any time a code usage is found (even if variable doesn't exist in the api)
=> feat: Refresh code usages on file save

src/utils/loadRepoConfig.ts
When loading the repo config file, set the project and org in the StateManager if available
=> Set project and org to state when loading repo config

media/styles/inspector.css, package.json, src/cli/UsagesCLIController.ts, src/commands/openCodeUsagesView/registerOpenUsagesViewCommand.ts, src/commands/refreshAll/registerRefreshAllCommand.ts, src/commands/refreshInspector/constants.ts, src/commands/refreshInspector/index.ts, src/commands/refreshInspector/registerInspectorCommand.ts, src/extension.ts, src/views/inspector/InspectorViewProvider.ts, src/webview/inspectorView.ts
- Added new section when workspace has more than one folder in inspector to show dropdown and selected folder
- only show `View Usages` button when selected folder has the usage for the variable selected
- Added optional param in `OpenUsagesCommand` to pass in a specific folder uri instead of the current open file's folder
=> feat: multiple folders in inspector view

src/commands/openInspectorView/registerOpenInspectorViewCommand.ts, src/views/inspector/InspectorViewProvider.ts
The `selectedType` was being set to `Variable` every time the key was being changed in the right dropdown. This was resulting in changing feature keys breaking. The `selectedType` shouldnt need to be set at all in that case since it gets updated when the left dropdown is used as well as when the inspector is first instantiated
=> fix selectedType resetting to Variable after changing feature key in dropdown

.github/workflows/runTests.yml
- skip integration tests for now as they're not ready yet
=> chore: skip integration tests on workflow

src/views/inspector/InspectorViewProvider.ts
Currently `getFeatureEnvironmentStatusesHTML` is being called for variables which results in 404 errors being shown each time the inspector re-renders
=> fix: don't evaluate getFeatureEnvironmentStatusesHTML for variables

media/styles/homeView.css, media/styles/inspector.css, media/styles/vscode.css, src/views/inspector/InspectorViewProvider.ts
* Add indent indicators to the Inspector View
* De-dup styles that were in both `inspector.css` and `homeView.css`
* Align the look of inspector folder selector to the figma mock up
=> chore: add indent indicators to the inspector view

src/views/inspector/InspectorViewProvider.ts, src/views/usages/UsagesTree/CodeUsageNode.ts
- Remove status and ID from details section in usages
- Add details to inspector that were previously only in usages
- Only show status on variables if the variable has been archived
- Removed description from usages since its not in the designs
=> Move details from usages to inspector, keep Created Date and Updated date in usages

src/webview/homeView.ts
**Cause**: using the homeSectionDropdowns for loop to attach to each edit config button caused this exception because there are two dropdowns yet only one edit config button so `document.getElementById('editConfigButton${i}')` would return `null`
**Fix**:  `document.getElementById('editConfigButton${i}')` will now be in a loop that iterates over a  list of elements that are queried for using `edit-config-button`
=> fix: exception in homeView.ts

media/inspector-white.svg, src/components/hoverCard.ts, src/views/usages/UsagesTree/CodeUsageNode.ts, src/views/usages/UsagesTree/UsagesTreeProvider.ts
Note: I think it would also be good to get rid of the details section from the usages tree, but that will break sorting. Gonna see if theres a way I can keep sorting working as is and just hide the details section so I don't need to completely redo how sorting usages works.
=> replace open in dashboard option with an inspector link in usages

src/extension.ts, src/views/inspector/InspectorViewProvider.ts, src/webview/inspectorView.ts
the previous event listeners for removing the focus style in the inspector view are too noisy
- remove the event listener from the editor
- remove the event listener in the inspector view when the focus style is cleared
- update the focus flow with `scrollIntoView()` to make sure the target get focused even in a shorter view
=> chore: remove and update event listeners for removing focus style

src/extension.ts
- didn't await `loginAndRefresh()` so `activeProjectKey` was undefined and resulting unselected project when two folders are opened
=> fix: project not set when two folders opened

src/views/inspector/InspectorViewProvider.test.ts, src/views/inspector/InspectorViewProvider.ts
- don't update the selectedKey if the currently selectedKey is still in the variables list. This is so that the selectedKey doesnt randomly change on refresh
- re-initialize features and variables when a new folder is added
- don't update the currently selected folder in the refresh function, that should never have been happening (afaik)
=> fix inspector to work properly with multiple folders open in the workspace

src/commands/openInspectorView/registerOpenInspectorViewCommand.ts, src/views/usages/UsagesTree/CodeUsageNode.ts
* Move inspector button in code usage node outside of details sub tree
* fix bug where inspector button did not work if a user did not have a file open in the current repo
=> fix: inspector button not working when no file is open

src/StateManager.ts, src/cli/AuthCLIController.ts, src/commands/refreshInspector/registerRefreshInspectorCommand.ts, src/extension.ts, src/utils/loginAndRefresh.test.ts, src/utils/loginAndRefresh.ts, src/views/environments/EnvironmentsTreeProvider.test.ts, src/views/environments/EnvironmentsTreeProvider.ts, src/views/home/HomeViewProvider.ts, src/views/inspector/InspectorViewProvider.test.ts, src/views/inspector/InspectorViewProvider.ts, src/views/login/LoginViewProvider.ts, src/views/usages/UsagesTree/UsagesTreeProvider.ts, src/webview/homeView.ts
Currently if one folder in the workspace is not logged in the extension will display the login view. This change allows the user to be logged in some folders but not others (for example, projects that don't use devcycle). If no folders are logged in the existing login view will be displayed.
- Track the logged in state of each folder
- Add method to login specific folder
- Display a login button in the home section if a folder is not logged in. All other sections will be empty
=> feat: Don't require all folders to be logged in

.github/actions/updateDocs/action.yml
Version should be `vX.Y.Z` but old action was generating `X.Y.Z` which caused 404s when the docs tried to fetch the readme
=> Add missing v to version in docs update

media/styles/homeView.css
- changed hovering style for buttons and icons to match theme
=> fix: made styling hovering buttons consistent with theme

src/cli/AuthCLIController.test.ts, src/cli/AuthCLIController.ts, src/cli/OrganizationsCLIController.test.ts, src/cli/OrganizationsCLIController.ts, src/constants.ts, src/extension.ts, src/utils/loginAndRefresh.ts
When the auto-login is triggered on workspace open or when adding folders, don't open a browser. We should only open the browser when the user had clicked the "login" button
=> fix: Don't open browser if logging in via auto-login

src/cli/VariablesCLIController.ts, src/views/inspector/InspectorViewProvider.test.ts, src/views/inspector/InspectorViewProvider.ts
- replaced `ID` with `Type` for variables in inspector details
- formatted `createdAt` and `updatedAt` to look nicer
=> chore: replaced ID with Type if it exists, and formatted createdAt and updatedAt

src/cli/EnvironmentsCLIController.ts, src/views/inspector/InspectorViewProvider.ts, src/views/inspector/index.ts, src/views/inspector/utils.ts
- display name and key in Feature dropdown: `Name (Key)`
- fixed slow switching of feature keys by not blocking html from rendering feature configurations
- when switching to a Feature, fetch the feature configuration and reload the inspector view when it finishes
https://github.com/DevCycleHQ/vscode-extension/assets/10345366/a9111c7b-6733-49aa-b020-a563bdf6c50e
New screenshot:
=> chore: show name and key for feature dropdown. Also improve loading of feature config statuses

media/styles/inspector.css, src/views/inspector/InspectorViewProvider.ts
- added extra css class for details value with link to ignore 50% width styling [here](https://github.com/DevCycleHQ/vscode-extension/pull/187/files#diff-084d91d4aa6b58d3c343d60f3c8aaaeed7b124c3d1e134d6aececb7a9a7e1f5aR524)
- rest of the changes are prettier changes
=> fix: fixed weird styling for feature link in inspector

src/cli/AuthCLIController.ts, src/utils/loginAndRefresh.test.ts, src/utils/loginAndRefresh.ts, src/views/login/LoginViewProvider.ts
- when using brand new project with vscode extension, it will give a blank screen since it will try to headless login with no repo config
- in this case, just go to login screen
- [this](https://github.com/DevCycleHQ/vscode-extension/pull/188/files#diff-9e8c06f26a79aa8c9d8c0d2e37fb068cdd422c6e9600f530c5c7aff92aead1b7R22) is the important change
=> fix: on login if headless login throws, go to login screen

media/styles/inspector.css, src/views/inspector/InspectorViewProvider.ts
* use `nowrap` on with CSS `white-space` property to stop text from wrapping in inspector view
* set inspector svg color in CSS
https://github.com/DevCycleHQ/vscode-extension/assets/33500361/c77f5211-942d-4012-bbde-f5dd886e421c
https://github.com/DevCycleHQ/vscode-extension/assets/33500361/8cf44f7d-d7f6-44c8-a8fd-a332e0f8530f
=> chore: don't let feature text wrap in inspector

src/extension.ts, src/utils/getLoggedInFolders.ts, src/utils/index.ts, src/utils/loginAndRefresh.test.ts, src/utils/loginAndRefresh.ts, src/views/inspector/InspectorViewProvider.test.ts, src/views/inspector/InspectorViewProvider.ts, src/views/inspector/utils.ts
- If multiple folders in workspace and one folder is logged out, make selected folder be the first logged in folder
=> fix: use first logged in folder for inspector view

src/views/inspector/utils.test.ts, src/views/inspector/utils.ts
- error happens if any variables or features present have no name somehow, default to sort by the key in these cases
=> fix: use key if no name defined in sortByName

media/styles/customDropdown.css
=> fix: hover color to match theme

src/cli/utils/loadCli.ts
Calling `bin/run` will use the version of node available in the user's path, calling `bin/dvc` will use the node version that is packaged with the CLI.
This ensures the extension is always using the correct node version
=> fix: Use node version that is bundled with CLI

package.json, src/cli/UsagesCLIController.ts, src/constants.ts, src/extension.ts, src/views/usages/UsagesTree/CodeUsageNode.ts, src/views/usages/UsagesTree/UsagesTreeProvider.ts, src/views/usages/UsagesTree/utils.test.ts, src/views/usages/UsagesTree/utils.ts, yarn.lock
- if calling `refresh` on `UsagesDataProvider` on save, pass in the saved file so that `dvc usages` is called with an `--include` flag to only get updated flags for the file saved
- this means we need to store matches per folder so that when we build the usages nodes we can remove/add any code usages nodes
- add tests for new utils functions
=> chore: only update usages for the saved file

webpack.config.js
- remove chunking when bundling with webpack to prevent multiple `extension` files from being generated
=> fix: reduce max chunk to one when webpacking

src/cli/OrganizationsCLIController.ts, src/cli/UsagesCLIController.ts, src/cli/utils/execShell.ts
* Update `execShell` to return `1` when there is no error code
* `usages` method now check if the CLI returned an error before processing the usages
=> fix: fix project showing up as undefined

src/constants.ts
- updated cli to fix variable aliases
- tested that variable aliases defined in devcycle config are showing up in usages
=> chore: update cli version to fix variable aliases

package.json, src/RudderStackService.ts, src/cli/utils/loadCli.ts, yarn.lock
- replace axios with fetch after upgrading broke the extension
=> fix: replace axios with fetch

src/extension.ts, src/utils/loginAndRefresh.ts, src/views/environments/registerEnvironmentsViewProvider.ts, src/views/home/registerHomeViewProvider.ts, src/views/inspector/registerInspectorViewProvider.ts, src/views/login/registerLoginViewProvider.ts, src/views/resources/registerResourcesProvider.ts, src/views/startup/registerStartupViewProvider.ts, src/views/usages/UsagesTree/UsagesTreeProvider.ts, src/views/usages/registerUsagesViewProvider.ts
- added additional debug logs to extension activation flow
=> chore: added additional debug logging to extension activation
