DevCycleHQ/vscode-extension

src/RudderStackService.ts, src/StateManager.ts, src/cli/baseCLIController.ts, src/cli/cliUtils.ts
* Update RudderStack track method to use Auth0 Id for userId
* Fix metrics tracking setting being cleared on every start up
=> chore: update RudderStack event tracking to use Auth0 id

.vscode/launch.json, .vscode/tasks.json, .vscodeignore, README.md, package.json, src/components/SidebarProvider.ts, webpack.config.js, yarn.lock
- replaced tsc script with webpack script
- moved button script to inline html script to save the headache of reading files with webpack
- replaced tasks locally with webpack, now needs an extension to get watch to work properly: https://marketplace.visualstudio.com/items?itemName=amodio.tsl-problem-matcher
=> chore: added webpack config

DEVELOPMENT.md, README.md
- Moved new development instructions to development.md
=> chore: moved development instructions to development.md

DEVELOPMENT.md, src/cli/BaseCLIController.ts, src/constants.ts, src/utils/setUpViews.ts, yarn.lock
- Create a function that checks `npm list` for the installed package version
- Parse the response and compare the version against the minimum required cli version using the semver lib.
- Slightly refactor the CliStartupView to include the version check and show an error if its incorrect
=> add min version check

src/cli/utils/loadCli.ts, src/constants.ts
Depends on CLI change: https://github.com/DevCycleHQ/cli/pull/258
=> chore: Add additional platform support

DEVELOPMENT.md, README.md, package.json, src/scripts/startup.ts, src/views/login/LoginViewProvider.ts, src/views/startup/StartupViewProvider.ts
- Remove setting to specify a CLI path
- Remove view + docs that prompt user to install CLI
=> chore: Remove requirement to install CLI

package.json, src/commands/openSettings/constants.ts, src/commands/openSettings/index.ts, src/commands/openSettings/registerOpenSettingsCommand.ts, src/extension.ts
- add settings button to sidebar nav
=> feat: add settings button to sidebar nav

src/cli/utils/loadCli.ts, src/constants.ts
Depends on CLI fix: https://github.com/DevCycleHQ/cli/pull/260
=> fix: Bump CLI version to fix parsing error on login

.github/workflows/release.yml, CHANGELOG.md
- updated changelog.md from prepare release step
=> chore: update changelog from prepare release step

package.json
- make auto login by default
*** to test it out, make sure you clear the setting for all profile first
=> chore: make auto login by default

src/views/environments/EnvironmentsTreeProvider.test.ts, src/views/environments/EnvironmentsTreeProvider.ts, src/views/environments/nodes.ts
- Sort environments by type
- Add unit tests to EnvironmentsTreeProvider
=> feat: Sort environments by type

media/styles/homeView.css, media/styles/resources.css, media/styles/vscode.css, package.json, src/RudderStackService.ts, src/StateManager.ts, src/cli/AuthCLIController.ts, src/cli/BaseCLIController.ts, src/cli/OrganizationsCLIController.ts, src/cli/ProjectsCLIController.ts, src/commands/refreshUsages/registerRefreshUsagesCommand.ts, src/constants.ts, src/extension.ts, src/views/home/HomeViewProvider.ts, src/views/home/index.ts, src/views/home/registerHomeViewProvider.ts, src/views/login/LoginViewProvider.ts, src/views/startup/StartupViewProvider.ts, src/webview/homeView.ts, webpack.config.js, yarn.lock
* add Home section
* logout button
* Organization selector (TODO: unset project and display empty state for variable usages - DVC-8557)
* Project selector
* `getAllProjects` now call `projects list` from the CLI since only project keys are needed
* update webpack config to load components from webview-ui-toolkit package
* Write integration tests
=> Dvc 8454 home view

media/styles/homeView.css, src/views/home/HomeViewProvider.ts
=> chore: move icons and logout button to same line

media/styles/resources.css, media/styles/vscode.css, src/views/home/HomeViewProvider.ts, src/views/resources/ResourcesViewProvider.ts
=> Dvc 8615 subheader styling

media/inspector.svg, media/styles/inspector.css, package.json, src/cli/FeaturesCLIController.ts, src/constants.ts, src/extension.ts, src/views/inspector/InspectorViewProvider.ts, src/views/inspector/index.ts, src/views/inspector/registerInspectorViewProvider.ts, src/webview/inspectorView.ts, webpack.config.js
- Added inspector sidebar, can choose between variables and features to show details and possible values (for variables)
=> feat: added inspector sidebar

src/extension.ts
When the repo config is saved, reload the config to state. This allows us to keep the alias map up to date so that the hover card is displayed appropriately
=> feat: Reload the repo config when file is saved

package.json, src/views/home/HomeViewProvider.ts, src/views/inspector/InspectorViewProvider.ts, src/views/resources/ResourcesViewProvider.ts, webpack.config.js, yarn.lock
- change `codiconsUri` to point to the `out` folder
- copy `codicon.css` and `codicon.ttf` from node_modules to the `out` folder
=> fix: copy codicon css to out folder

src/views/environments/EnvironmentsTreeProvider.test.ts, src/views/environments/nodes.ts
- rename keys to sdk keys in environments section
=> chore: rename keys to sdk keys

src/utils/redactSdkKey.ts, src/views/environments/EnvironmentsTreeProvider.test.ts, src/views/environments/nodes.ts
=> chore: add truncated sdk keys to env section

src/cli/UsagesCLIController.ts, src/views/inspector/InspectorViewProvider.test.ts, src/views/inspector/InspectorViewProvider.ts
- added unit test file for inspector view
=> chore: added unit test file for inspector

media/styles/vscode.css
=> chore: fix read our docs link

media/styles/homeView.css, media/styles/inspector.css, media/styles/vscode.css, src/views/home/HomeViewProvider.ts, src/views/inspector/InspectorViewProvider.ts
=> chore: make Home View dropdown fill sidebar width

media/inspector-white.svg, media/inspector.svg, media/styles/inspector.css, src/views/inspector/InspectorViewProvider.ts
- use inline svg to change fill color to match codicons
=> chore: made styling colour for inspector consistent throughout extension

media/styles/inspector.css, src/views/inspector/InspectorViewProvider.ts
- add environment statuses to feature in inspector view
=> feat: add environment statuses to feature

src/views/inspector/InspectorViewProvider.ts
- JSON stringified possible values
=> fix: json stringify possible values due to possible values possibly being JSON

src/views/inspector/InspectorViewProvider.ts
**Cause**: When logging out, the webview for the InspectorViewProvider get's disposed. We call `executeRefreshAllCommand` right after logging in which eventually causes the InspectorViewProvider to update the html for it's webview but since it's disposed, the `Webivew is disposed` exception is thrown.
**Fix**: In the `onDidDispose` event handler for the InspectorViewProvider webview, set the `webviewIsDisposed` instance variable to true and check this variables value when refreshing the inspector view.
=> fix: Webview is disposed error on login

src/commands/refreshAll/registerRefreshAllCommand.ts, src/extension.ts, src/views/home/HomeViewProvider.ts
- add homeViewProvider to refreshProviders, so home view can be refreshed whenever there're updates
- add refresh method to home view provider
=> chore: add homeViewProvider to refreshProviders

src/cli/cliUtils.ts
- removed getting feature configurations code from `getCombinedVariableDetails` as it was redundant
=> chore: removed feature configurations from hover as it was not used

src/extension.ts
- handle case where removing folder should also refresh usages of any current workspace folders
=> fix: on remove of folder refresh folders

media/styles/customDropdown.css, package.json, src/cli/FeaturesCLIController.ts, src/views/inspector/InspectorViewProvider.ts, src/webview/inspectorView.ts, yarn.lock
- add fuse.js to do fuzzy search
- add custom dropdown to match vscode style and handle search in dropdown
- handle dropdown for features and variables
different themes:
=> feat: add fuzzy search to variables/features dropdown in inspector view

README.md
- add badge to readme for min vscode version
=> chore: add badge to readme for min vscode version

src/constants.ts
This reverts commit e0abe0a974b784aa5823142c42cd968cab8edb74.
=> Revert "Bump CLI to v5.10.2 (#191)"

src/components/fuzzySearch.ts, src/views/inspector/InspectorViewProvider.ts, src/webview/inspectorView.ts
- add helper functions for fuzzy search dropdown to make it more reusable
=> chore: add helper functions for fuzzy search dropdown

src/views/usages/UsagesTree/UsagesTreeProvider.ts
- add no usages message to variable usages section
=> chore: add no usages message

src/cli/ProjectsCLIController.test.ts, src/cli/ProjectsCLIController.ts, src/constants.ts, src/views/home/HomeViewProvider.ts
- sort projects dropdown list
- display projects name instead of key in dropdown
=> chore: sort projects and display projects name

src/components/fuzzySearch.ts, src/views/home/HomeViewProvider.ts, src/views/inspector/InspectorViewProvider.ts, src/webview/homeView.ts, src/webview/inspectorView.ts
- add fuzzy search to projects list dropdown
- update localStorage handling to avoid null in localStorage
- handle multi folder dropdowns
=> feat: add fuzzy search to projects list dropdown

package.json, yarn.lock
This reverts commit ddad1529f6aae2ebb9951c1d52b36caf634feffc.
=> chore(deps): Revert bump axios from 0.26.1 to 1.6.0

src/cli/utils/loadCli.ts
=> chore: added caught error to message

yarn.lock
=> chore: update braces dep

package.json, yarn.lock
=> fix: add cross-spawn resolution to fix vuln

package.json, yarn.lock
=> chroe: update serialize-javascript
